### ISSUE TITLE
Normal players incorrectly retain spirit abilities and movement

### ISSUE THREAD

**Issue by Goldenschmidt** [EtiTheSpirit/TheOriMod#5]
**What happens?**
You retain your heightened jump, and your health isn't updated until you take damage or rejoin the world.
[video.mp4 [Dropbox]](https://www.dropbox.com/s/lyh48pocxfn861m/2023-01-11%20-%20Minecraft%201.19.2%2022%2030%2004.mp4?dl=0)

**How do I cause it?**
Literally just be a spirit, then write in `/spirit set <player> false` and press enter. You retain the heightened jump from the spirit state, and the health doesn't update till after damage has been taken.

**Is this bug so bad that you find it nearly impossible to play?**
You can still play, and does not feel anything different when just playing as a spirit. But normal players will have a higher jump than normal (can jump 2 blocks instead of 1)

**Log file**
There is no Debug.Log, but I can give you the `latest.log`.
[latest.log](https://github.com/EtiTheSpirit/TheOriMod/files/10396133/latest.log)

**Comment by EtiTheSpirit** [comment]
This has been fixed in RC3 (which is not yet released), however the health rendering issue is a bug with Minecraft itself and so fixing that may prove to be more challenging and/or out of the scope of this mod.

**Comment by Goldenschmidt** [comment]
This issue is still present on servers, with the added issue of still being in spirit form, in RC3.
[Video.mp4 [Dropbox]](https://www.dropbox.com/s/kdtusepsk1hif8d/Minecraft_%201.19.2%202023-01-17%2010-22-49.mp4?dl=0)
[debug.log](https://github.com/EtiTheSpirit/TheOriMod/files/10433510/debug.log)

**Comment by Goldenschmidt** [comment]
Additional testing shows that the Default State set in the world's own config file, determines what state you'll truly will be in.

Doesn't matter what you do in-game.

If the Default State is set to False, you will be normal-sized, and have no abilities apart from not taking fall damage, and the increased running speed. Oh, and the lowered health.
This is if you write in the command in-game to set yourself to true.

If the Default State is set to True, you will be spirit-sized, and have the abilities you has unlocked for yourself. You're just at normal walking speed, and you can take fall damage.
This is if you write in the command in-game to set yourself to false.

**Comment by EtiTheSpirit** [comment]
This issue relates to a few networking issues it seems.

~~There are a few things I will do to fix this and also make debugging easier, notably including an expansion of the `/spirit` command to introduce the ability to change some configs.~~

Edit: This command change is not feasible.

**Comment by EtiTheSpirit** [comment]
Alright, I got the networking issue fixed. It will be out in RC4.

It is worth it to note that you cannot change server configs while the server is running, it must be fully stopped and restarted.

**Comment by EtiTheSpirit** [comment]
Just a status update, I am finalizing this as well as a few other fixes and feature tweaks.

**Comment by EtiTheSpirit** [comment]
Alright here, I don't know how good of an idea this is to link here like this, but I don't wanna do a full blown RC4 release quite yet since there's some stragglers I have in the features (my buddy is doing a German translation, I added a missing food item).

Try this out and see if the issue is fixed. There was one issue I had a friend report which is where health rendering temporarily breaks upon changing dimensions, I don't know if that is localized or it happens here too.

[orimod RC4.zip](https://github.com/EtiTheSpirit/TheOriMod/files/10482508/orimod.RC4.zip)

**Comment by Goldenschmidt** [comment]
It has been fixed. Now, I haven't tested it with a friend in the server included though, so I cannot tell if it also changes on their end.
I will try to get a test buddy during this week to help me test the mod in a server environment. My previous buddy has terrible internet right now, so not capable.

Will respond here once I figure something out, whether it is 100% fixed, or not.

**Comment by EtiTheSpirit** [comment]
Alright, thanks. I did a local test with one of my friends and it seemed to work fine for us, we just want to double check. We have time anyway since said friend is still not done with the translation, but chances are this will be the proper 2.0.0 release.

**Comment by Goldenschmidt** [comment]
So while testing RC4 with a friend on a Dedicated server.
The friend and myself does change form and does gets our abilities added/removed when switching state.
But we found two more issues.

- [ #12 ]  Do not know how this happens at all, or how to recreate it. It just randomly happened when my friend got close to me.

- [ #13 ]  Sneaking is broken in Server as normal player. You can see your own character sneaking, but your view doesn't go down, nor can you see other people sneak.

~~I will make a new issue for both, and link them here.~~
But otherwise, the original issue here is solved, basically.

**Comment by EtiTheSpirit** [comment]
This is now fixed in 2.0.0, which will be releasing shortly after this closure.
